Update commands for code liniting in contributing guidelines
huggingface/trl pull request #2225
Opened 2024-10-12 00:10 UTC by Ben-Schneider-code

# What does this PR do?
As I was looking to for the code linting commands for a pr, I was confused by what I think is missing linting commands. It looks like a bad copy/paste?

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a GitHub issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/trl/tree/main/docs).
- [ ] Did you write any new necessary tests?

2024-10-12 09:20 UTC, qgallouedec commented
Good catch @Ben-Schneider-code, thanks for reporting. I'd like to take this opportunity to be a little more specific about what our precommit does. Here's a suggestion:

````md
TRL relies on `ruff` for maintaining consistent code formatting across its source files. Before submitting any PR, you should apply automatic style corrections and run code verification checks.

We provide a `precommit` target in the `Makefile` that simplifies this process by running all required checks and optimizations on only the files modified by your PR.

To apply these checks and corrections in one step, use:

```bash
$ make precommit
```

This command runs the following:
- Executes `pre-commit` hooks to automatically fix style issues with `ruff` and other tools.
- Runs additional scripts such as adding copyright information.

If you prefer to apply the style corrections separately or review them individually, the `pre-commit` hook will handle the formatting for the files in question.
````

2024-10-12 21:52 UTC, Ben-Schneider-code commented
@qgallouedec  done 👍

2024-10-13 05:59 UTC, qgallouedec requested changes

2024-10-13 05:59 UTC, qgallouedec commented on CONTRIBUTING.md
> +<br>
```suggestion
```

2024-10-13 05:59 UTC, qgallouedec commented on CONTRIBUTING.md
> +TRL relies on `ruff` for maintaining consistent code formatting across its source files. Before submitting any PR, you should apply automatic style corrections and run code verification checks.
```suggestion
    TRL relies on `ruff` for maintaining consistent code formatting across its source files. Before submitting any PR, you should apply automatic style corrections and run code verification checks.
```

2024-10-13 05:59 UTC, qgallouedec commented on CONTRIBUTING.md
> +We provide a `precommit` target in the `Makefile` that simplifies this process by running all required checks and optimizations on only the files modified by your PR.
```suggestion
    We provide a `precommit` target in the `Makefile` that simplifies this process by running all required checks and optimizations on only the files modified by your PR.
```

2024-10-13 05:59 UTC, qgallouedec commented on CONTRIBUTING.md
> +To apply these checks and corrections in one step, use:
```suggestion
    To apply these checks and corrections in one step, use:
```

2024-10-13 05:59 UTC, qgallouedec commented on CONTRIBUTING.md
> +If you prefer to apply the style corrections separately or review them individually, the `pre-commit` hook will handle the formatting for the files in question.
````suggestion
    This command runs the following:
    - Executes `pre-commit` hooks to automatically fix style issues with `ruff` and other tools.
    - Runs additional scripts such as adding copyright information.

    If you prefer to apply the style corrections separately or review them individually, the `pre-commit` hook will handle the formatting for the files in question.
````

2024-10-13 07:13 UTC, qgallouedec approved these changes

2024-10-13 07:21 UTC, qgallouedec commented
Thanks a lot @Ben-Schneider-code!

2024-10-13 07:22 UTC, merged